name: ServerPlugin
main: org.bear.serverPlugin.ServerPlugin
version: 1.0
api-version: 1.21
commands:
  phone:
    description: Gives you the Magic Soil item
    usage: /phone
  is:
    description: Teleport to your own island
    usage: /is