name: ServerPlugin
main: org.bear.serverPlugin.ServerPlugin
version: 1.0
api-version: 1.21
commands:
  is:
    description: Teleport to your own island
    usage: /is
  reset:
    description: resets player variables
    usage: /reset